name: continuous-integration-continuous-delivery
on:
  push:
   branches: ['main']
  workflow_dispatch:

jobs: 
  job-build:

    name: build
    uses: enzoovizotto/ci-cd-reutilizavel-front/.github/workflows/build_template.yml@main
    with:
      node-version: 20

  job-deploy:
    needs: job-build

    name: deploy
    uses: enzoovizotto/ci-cd-reutilizavel-front/.github/workflows/deploy_tempalte.yml@main
    with:
      environment: prod
      publish-profile: "AZURE_PUBLISH_PROFILE_FRONT"
    secrets: inherit