name: continuous-integration-continuous-delivery
on:
  push:
   branches: ['main']

jobs: 
  job-build:
    runs-on: ubuntu-latest

    steps: 
    - name: checkout repository
      uses: actions/checkout@v4.1.7
    - name: using node
      uses: actions/setup-node@v4.0.3
      with: 
        node-version: 22.x
    - name: run 
      run: | 
        cd ci-cd-vite
        npm install
        npm run build
    - name: 'Zip build'
      shell: bash
      run: |
        pushd ./dist
        zip -r artifact.zip
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: dist/artifact.zip
        if-no-files-found: error

  job-deploy:
    runs-on: ubuntu-latest
    needs: job-build

    steps: 
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: artifact

    - name: "Unzip Artifact"
      shell: bash
      run: |
        unzip artifact.zip -d .
        rm artifact.zip
        
    - name: Azure functions deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        azure_static_web_apps_api_token: ${{secrets.AZURE_PUBLISH_PROFILE_FRONT }}
        action: "upload"
        app_location: "/"
        app_artifact_location: "/"
        skip_app_build: true
