name: continuous-integration-continuous-delivery
on:
  push:
   branches: ['main']

jobs: 
  job-build:
    runs-on: ubuntu-latest

    steps: 
    - name: checkout repository
      uses: actions/checkout@v4.1.7
    - name: using node
      uses: actions/setup-node@v4.0.3
      with: 
        node-version: 22.x
    - name: run 
      run: | 
        cd ci-cd-vite
        npm install
        npm run build
    - name: upload artefacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: artifact
        path: .

  job-deploy:
    runs-on: ubuntu-latest
    needs: job-build

    steps: 
    - name: download artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: artifact
        path: .
    - name: Azure functions deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        app-name: "ci-cd-frontend"
        publish-profile: ${{secrets.azure_publish_profile_front}}
